// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for App controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions } from "../models";

@Injectable({ providedIn: "root" })
export class ApiAppProducer {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    appControllerGetFile(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    appControllerGetFile(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    appControllerGetFile(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    appControllerGetFile(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/file`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    appControllerUpload(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    appControllerUpload(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    appControllerUpload(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    appControllerUpload(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/upload`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('post', url, {
            body: null,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    appControllerImage(observe?: 'body', options?: RequestOptions<'text'>): Observable<number>;
    appControllerImage(observe?: 'response', options?: RequestOptions<'text'>): Observable<HttpResponse<number>>;
    appControllerImage(observe?: 'events', options?: RequestOptions<'text'>): Observable<HttpEvent<number>>;
    appControllerImage(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/image`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: null,
            observe,
            headers,
            responseType: 'text',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    appControllerFakeHandlerThree(page: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    appControllerFakeHandlerThree(page: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    appControllerFakeHandlerThree(page: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    appControllerFakeHandlerThree(page: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/patterns/paginated`;

        let params = new HttpParams();
        if (page != null) {
            params = HttpParamsBuilder.addToHttpParams(params, page, 'page');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
