// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Categories controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, CategoriesDto, CreateCategoryDto, CategoryDto, CategoriesPaginatedPageDto } from "../models";

@Injectable({ providedIn: "root" })
export class ApiCategoriesProducer {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    categoriesControllerAll(observe?: 'body', options?: RequestOptions<'json'>): Observable<CategoriesDto>;
    categoriesControllerAll(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CategoriesDto>>;
    categoriesControllerAll(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CategoriesDto>>;
    categoriesControllerAll(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/categories/all`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    categoriesControllerCreate(createCategoryDto: CreateCategoryDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<CategoryDto>;
    categoriesControllerCreate(createCategoryDto: CreateCategoryDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CategoryDto>>;
    categoriesControllerCreate(createCategoryDto: CreateCategoryDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CategoryDto>>;
    categoriesControllerCreate(createCategoryDto: CreateCategoryDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/categories/create`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: createCategoryDto,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    categoriesControllerEntity(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<CategoryDto>;
    categoriesControllerEntity(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CategoryDto>>;
    categoriesControllerEntity(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CategoryDto>>;
    categoriesControllerEntity(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/categories/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    categoriesControllerRemove(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    categoriesControllerRemove(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    categoriesControllerRemove(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    categoriesControllerRemove(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/categories/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    categoriesControllerPage(page: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<CategoriesPaginatedPageDto>;
    categoriesControllerPage(page: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CategoriesPaginatedPageDto>>;
    categoriesControllerPage(page: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CategoriesPaginatedPageDto>>;
    categoriesControllerPage(page: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/categories/list/${page}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    categoriesControllerEdit(id: number, createCategoryDto: CreateCategoryDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<CategoryDto>;
    categoriesControllerEdit(id: number, createCategoryDto: CreateCategoryDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CategoryDto>>;
    categoriesControllerEdit(id: number, createCategoryDto: CreateCategoryDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CategoryDto>>;
    categoriesControllerEdit(id: number, createCategoryDto: CreateCategoryDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/categories/edit/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('patch', url, {
            body: createCategoryDto,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
