// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated service exports
* Do not edit this file manually
*/
export { ApiAdminProducer } from "./admin.service";
export { ApiAppProducer } from "./app.service";
export { ApiCategoriesProducer } from "./categories.service";
export { ApiFilesProducer } from "./files.service";
export { ApiImagesProducer } from "./images.service";
export { ApiOrdersProducer } from "./orders.service";
export { ApiPatternsProducer } from "./patterns.service";
export { ApiSizesProducer } from "./sizes.service";
export { ApiUserProducer } from "./user.service";
