// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Orders controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, CartDto, InputShortOrderPatternDto, NumberEntityDto } from "../models";

@Injectable({ providedIn: "root" })
export class ApiOrdersProducer {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    ordersControllerCart(observe?: 'body', options?: RequestOptions<'json'>): Observable<CartDto>;
    ordersControllerCart(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CartDto>>;
    ordersControllerCart(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CartDto>>;
    ordersControllerCart(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/orders/cart`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    ordersControllerClearAll(observe?: 'body', options?: RequestOptions<'json'>): Observable<CartDto>;
    ordersControllerClearAll(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CartDto>>;
    ordersControllerClearAll(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CartDto>>;
    ordersControllerClearAll(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/orders/cart`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    ordersControllerAddItemToCart(inputShortOrderPatternDto: InputShortOrderPatternDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<CartDto>;
    ordersControllerAddItemToCart(inputShortOrderPatternDto: InputShortOrderPatternDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CartDto>>;
    ordersControllerAddItemToCart(inputShortOrderPatternDto: InputShortOrderPatternDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CartDto>>;
    ordersControllerAddItemToCart(inputShortOrderPatternDto: InputShortOrderPatternDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/orders/cart/add`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('patch', url, {
            body: inputShortOrderPatternDto,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    ordersControllerMergeLocalCart(requestBody: Array<InputShortOrderPatternDto>, observe?: 'body', options?: RequestOptions<'json'>): Observable<CartDto>;
    ordersControllerMergeLocalCart(requestBody: Array<InputShortOrderPatternDto>, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CartDto>>;
    ordersControllerMergeLocalCart(requestBody: Array<InputShortOrderPatternDto>, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CartDto>>;
    ordersControllerMergeLocalCart(requestBody: Array<InputShortOrderPatternDto>, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/orders/cart/merge`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('patch', url, {
            body: requestBody,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    ordersControllerRemoveItemFromCart(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<CartDto>;
    ordersControllerRemoveItemFromCart(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CartDto>>;
    ordersControllerRemoveItemFromCart(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CartDto>>;
    ordersControllerRemoveItemFromCart(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/orders/cart/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    localCartControllerLocalCartPrice(requestBody: Array<InputShortOrderPatternDto>, observe?: 'body', options?: RequestOptions<'json'>): Observable<NumberEntityDto>;
    localCartControllerLocalCartPrice(requestBody: Array<InputShortOrderPatternDto>, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<NumberEntityDto>>;
    localCartControllerLocalCartPrice(requestBody: Array<InputShortOrderPatternDto>, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<NumberEntityDto>>;
    localCartControllerLocalCartPrice(requestBody: Array<InputShortOrderPatternDto>, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/orders/cart/local/price`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: requestBody,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
