// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Patterns controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { CreatePatternDto, RequestOptions, SuccessCreateDto, PatternsPaginatedPageDto, FullPatternEntityDto } from "../models";

@Injectable({ providedIn: "root" })
export class ApiPatternsProducer {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    patternsControllerCreate(createPatternDto: CreatePatternDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<SuccessCreateDto>;
    patternsControllerCreate(createPatternDto: CreatePatternDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SuccessCreateDto>>;
    patternsControllerCreate(createPatternDto: CreatePatternDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SuccessCreateDto>>;
    patternsControllerCreate(createPatternDto: CreatePatternDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/patterns/create`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: createPatternDto,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    patternsControllerPage(page: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<PatternsPaginatedPageDto>;
    patternsControllerPage(page: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PatternsPaginatedPageDto>>;
    patternsControllerPage(page: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PatternsPaginatedPageDto>>;
    patternsControllerPage(page: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/patterns/list/${page}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    patternsControllerByIds(id: Array<string>, observe?: 'body', options?: RequestOptions<'json'>): Observable<Record<string, any>>;
    patternsControllerByIds(id: Array<string>, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Record<string, any>>>;
    patternsControllerByIds(id: Array<string>, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Record<string, any>>>;
    patternsControllerByIds(id: Array<string>, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/patterns/ids`;

        let params = new HttpParams();
        if (id != null) {
            params = HttpParamsBuilder.addToHttpParams(params, id, 'id');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    patternsControllerEdit(id: number, createPatternDto: CreatePatternDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<SuccessCreateDto>;
    patternsControllerEdit(id: number, createPatternDto: CreatePatternDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SuccessCreateDto>>;
    patternsControllerEdit(id: number, createPatternDto: CreatePatternDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SuccessCreateDto>>;
    patternsControllerEdit(id: number, createPatternDto: CreatePatternDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/patterns/edit/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('patch', url, {
            body: createPatternDto,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    patternsControllerEntity(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<FullPatternEntityDto>;
    patternsControllerEntity(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FullPatternEntityDto>>;
    patternsControllerEntity(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FullPatternEntityDto>>;
    patternsControllerEntity(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/patterns/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
