// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Sizes controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, SizesDto, CreateSizeDto, SizeDto, SizesPaginatedPageDto } from "../models";

@Injectable({ providedIn: "root" })
export class ApiSizesProducer {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    sizesControllerAll(observe?: 'body', options?: RequestOptions<'json'>): Observable<SizesDto>;
    sizesControllerAll(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SizesDto>>;
    sizesControllerAll(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SizesDto>>;
    sizesControllerAll(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/sizes/all`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    sizesControllerCreate(createSizeDto: CreateSizeDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<SizeDto>;
    sizesControllerCreate(createSizeDto: CreateSizeDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SizeDto>>;
    sizesControllerCreate(createSizeDto: CreateSizeDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SizeDto>>;
    sizesControllerCreate(createSizeDto: CreateSizeDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/sizes/create`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: createSizeDto,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    sizesControllerEntity(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<SizeDto>;
    sizesControllerEntity(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SizeDto>>;
    sizesControllerEntity(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SizeDto>>;
    sizesControllerEntity(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/sizes/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    sizesControllerRemove(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    sizesControllerRemove(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    sizesControllerRemove(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    sizesControllerRemove(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/sizes/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    sizesControllerPage(page: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<SizesPaginatedPageDto>;
    sizesControllerPage(page: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SizesPaginatedPageDto>>;
    sizesControllerPage(page: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SizesPaginatedPageDto>>;
    sizesControllerPage(page: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/sizes/list/${page}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    sizesControllerEdit(id: number, createSizeDto: CreateSizeDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<SizeDto>;
    sizesControllerEdit(id: number, createSizeDto: CreateSizeDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SizeDto>>;
    sizesControllerEdit(id: number, createSizeDto: CreateSizeDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SizeDto>>;
    sizesControllerEdit(id: number, createSizeDto: CreateSizeDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/sizes/edit/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('patch', url, {
            body: createSizeDto,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
