// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for User controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { UserCredentialsDto, RequestOptions, SuccessCreateDto, UserTokensDTO, RefreshTokenCredentialsDto, LogoutCredentialsDto, UserProfileDto } from "../models";

@Injectable({ providedIn: "root" })
export class ApiUserProducer {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    userControllerRegister(userCredentialsDto: UserCredentialsDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<SuccessCreateDto>;
    userControllerRegister(userCredentialsDto: UserCredentialsDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SuccessCreateDto>>;
    userControllerRegister(userCredentialsDto: UserCredentialsDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SuccessCreateDto>>;
    userControllerRegister(userCredentialsDto: UserCredentialsDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/user/user/register`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: userCredentialsDto,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    userControllerSignIn(userCredentialsDto: UserCredentialsDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserTokensDTO>;
    userControllerSignIn(userCredentialsDto: UserCredentialsDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserTokensDTO>>;
    userControllerSignIn(userCredentialsDto: UserCredentialsDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserTokensDTO>>;
    userControllerSignIn(userCredentialsDto: UserCredentialsDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/user/user/sign-in`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: userCredentialsDto,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    userControllerRefresh(refreshTokenCredentialsDto: RefreshTokenCredentialsDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserTokensDTO>;
    userControllerRefresh(refreshTokenCredentialsDto: RefreshTokenCredentialsDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserTokensDTO>>;
    userControllerRefresh(refreshTokenCredentialsDto: RefreshTokenCredentialsDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserTokensDTO>>;
    userControllerRefresh(refreshTokenCredentialsDto: RefreshTokenCredentialsDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/user/user/refresh`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: refreshTokenCredentialsDto,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    userControllerLogout(logoutCredentialsDto: LogoutCredentialsDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    userControllerLogout(logoutCredentialsDto: LogoutCredentialsDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    userControllerLogout(logoutCredentialsDto: LogoutCredentialsDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    userControllerLogout(logoutCredentialsDto: LogoutCredentialsDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/user/user/logout`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: logoutCredentialsDto,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    userControllerProfile(observe?: 'body', options?: RequestOptions<'json'>): Observable<UserProfileDto>;
    userControllerProfile(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserProfileDto>>;
    userControllerProfile(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserProfileDto>>;
    userControllerProfile(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/user/user/profile`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
