// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface UserCredentialsDto {
    /** User email */
    email: string;
    /** User password */
    password: string;
}

export interface SuccessCreateDto {
    /** Id of entity */
    id: number;
}

/** Code of error */
export enum EnumApiErrorCodes {
    ALREADY_EXIST = "ALREADY_EXIST",
    INVALID_PASSWORD = "INVALID_PASSWORD",
    INVALID_EMAIL = "INVALID_EMAIL",
    NOT_EXIST = "NOT_EXIST",
    INCORRECT_PASSWORD = "INCORRECT_PASSWORD",
    EXPIRED = "EXPIRED",
    NOT_UNIQUE = "NOT_UNIQUE"
}

/** Error entity name */
export enum EnumApiEntityNames {
    Category = "category",
    Size = "size",
    Pattern = "pattern",
    PatternSize = "patternSize",
    File = "file"
}

export interface ErrorsDto {
    /** Code of error */
    code: EnumApiErrorCodes;
    /** Error entity name */
    entity?: EnumApiEntityNames;
}

export interface UserTokensDTO {
    /** Access token */
    access: string;
    /** Refresh token */
    refresh: string;
}

export interface RefreshTokenCredentialsDto {
    /** Access token */
    access: string;
    /** Refresh token */
    refresh: string;
}

export interface LogoutCredentialsDto {
    /** Access token */
    access: string;
    /** Refresh token */
    refresh: string;
}

/** Users role */
export enum EnumUserRole {
    Common = "common",
    Admin = "admin"
}

export interface NumberEntityDto {
    /** Russian number */
    ru: number;
    /** English number */
    en?: number;
}

export interface PatternWithPriceDto {
    /** Id of entity */
    id: number;
    /** Id of entity */
    createdAt?: Date;
    /** Id of entity */
    updatedAt?: Date;
    /** Base price of pattern */
    basePrice: NumberEntityDto;
    /** Additional price of pattern */
    additionalPrice: NumberEntityDto;
    /** Color price of pattern */
    colorPrice: NumberEntityDto;
}

export interface ShortOrderPatternDto {
    /** Id of entity */
    id: number;
    /** Id of entity */
    createdAt?: Date;
    /** Id of entity */
    updatedAt?: Date;
    /** Sizes ids */
    sizes: Array<number>;
    /** Status of colors able */
    color: boolean;
    /** Status of colors able */
    bought: boolean;
    /** Pattern with prices */
    pattern: PatternWithPriceDto;
}

/** Order status */
export enum EnumOrderStatus {
    Cancel = "cancel",
    Open = "open",
    Success = "success"
}

export interface UserOrderDto {
    /** Id of entity */
    id: number;
    /** Id of entity */
    createdAt?: Date;
    /** Id of entity */
    updatedAt?: Date;
    /** Order status */
    status: EnumOrderStatus;
    /** Patterns */
    patterns: Array<ShortOrderPatternDto>;
}

export interface UserProfileDto {
    /** Id of entity */
    id: number;
    /** Id of entity */
    createdAt?: Date;
    /** Id of entity */
    updatedAt?: Date;
    /** Email of user */
    email: string;
    /** Users name */
    username: string;
    /** Users role */
    role: EnumUserRole;
    /** Bought patterns */
    ownPatterns: Array<ShortOrderPatternDto>;
    /** Current cart */
    cart: UserOrderDto;
}

export interface LabelEntityDto {
    /** Russian label */
    ru: string;
    /** English label */
    en?: string;
}

export interface CategoryDto {
    /** Label of category */
    label: LabelEntityDto;
    /** English label */
    id: string;
    /** Date of creating at */
    createdAt: Date;
}

export interface CategoriesDto {
    /** List of categories */
    items: Array<CategoryDto>;
}

export interface CreateCategoryDto {
    /** Russian label */
    ru: string;
    /** English label */
    en?: string;
}

export interface CategoriesPaginatedPageDto {
    /** Current page */
    page: number;
    /** Count of pages */
    count: number;
    /** Paginated categories */
    items: Array<CategoryDto>;
}

export interface SizeDto {
    /** Value of size */
    value: number;
    /** Entity id */
    id: number;
    /** Date of creating at */
    createdAt: Date;
}

export interface SizesDto {
    /** List of sizes */
    items: Array<SizeDto>;
}

export interface CreateSizeDto {
    /** Value of size */
    value: number;
}

export interface SizesPaginatedPageDto {
    /** Current page */
    page: number;
    /** Count of pages */
    count: number;
    /** Paginated sizes */
    items: Array<SizeDto>;
}

export interface PatternSizeDto {
    /** Id of entity */
    id: number;
    /** Cbb file id */
    cbb: number;
    /** Pdf file id */
    pdf: number;
    /** Png file id */
    png: number;
    /** Jbb file id */
    jbb: number;
    /** Size id */
    size: number;
}

export interface CreatePatternDto {
    /** Name of pattern */
    name: LabelEntityDto;
    /** Description of pattern */
    description: LabelEntityDto;
    /** Base price of pattern */
    basePrice: NumberEntityDto;
    /** Additional price of pattern */
    additionalPrice: NumberEntityDto;
    /** Color price of pattern */
    colorPrice: NumberEntityDto;
    /** Pattern visible status */
    hidden: boolean;
    /** Colors of pattern */
    color: number;
    /** Pattern images */
    images: Array<number>;
    /** Categories of pattern */
    categories: Array<number>;
    /** Sizes of pattern */
    sizes: Array<PatternSizeDto>;
}

export interface ImageDto {
    /** Id of entity */
    id: number;
    /** Name of image */
    name: string;
    /** Preview image path */
    preview: string;
    /** Full image path */
    full: string;
}

export interface FileDto {
    /** Id of entity */
    id: number;
    /** Name of file */
    name: string;
    /** File path */
    path: string;
}

export interface PatternEntityDto {
    /** Id of entity */
    id: number;
    /** Name of pattern */
    name: LabelEntityDto;
    /** Description of pattern */
    description: LabelEntityDto;
    /** Base price of pattern */
    basePrice: NumberEntityDto;
    /** Additional price of pattern */
    additionalPrice: NumberEntityDto;
    /** Color price of pattern */
    colorPrice: NumberEntityDto;
    /** Pattern visible status */
    hidden: boolean;
    /** Ids of categories */
    categories: Array<number>;
    /** Pattern images */
    images: Array<ImageDto>;
    /** Color file of pattern */
    color: FileDto;
    /** Sizes of pattern */
    sizes: Array<PatternSizeDto>;
}

export interface PatternsPaginatedPageDto {
    /** Current page */
    page: number;
    /** Count of pages */
    count: number;
    /** Paginated patterns */
    items: Array<PatternEntityDto>;
}

export interface FullPatternSizeDto {
    /** Id of entity */
    id: number;
    /** Cbb file id */
    cbb: number;
    /** Pdf file id */
    pdf: number;
    /** Png file id */
    png: number;
    /** Jbb file id */
    jbb: number;
    /** Size id */
    size: SizeDto;
}

export interface FullPatternEntityDto {
    /** Id of entity */
    id: number;
    /** Name of pattern */
    name: LabelEntityDto;
    /** Description of pattern */
    description: LabelEntityDto;
    /** Base price of pattern */
    basePrice: NumberEntityDto;
    /** Additional price of pattern */
    additionalPrice: NumberEntityDto;
    /** Color price of pattern */
    colorPrice: NumberEntityDto;
    /** Pattern visible status */
    hidden: boolean;
    /** Ids of categories */
    categories: Array<number>;
    /** Pattern images */
    images: Array<ImageDto>;
    /** Color file of pattern */
    color: FileDto;
    /** Sizes of pattern */
    sizes: Array<FullPatternSizeDto>;
}

export interface InputShortOrderPatternDto {
    /** Id of entity */
    id: number;
    /** Id of entity */
    createdAt?: Date;
    /** Id of entity */
    updatedAt?: Date;
    /** Sizes ids */
    sizes: Array<number>;
    /** Status of colors able */
    color: boolean;
    /** Status of colors able */
    bought: boolean;
    /** Pattern id */
    pattern: number;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
